### ISSUE TITLE
make install does not run

### ISSUE THREAD

**Issue by xv09** [ayqxiong/FinalProject3#2]
Hi Annabelle,

I tried to run "make install" but the terminal returns "make: nothing to be done for "install"" -- please see attached SC.

<img width="442" alt="Screen Shot 2024-04-19 at 11 36 51 PM" src="https://github.com/ayqxiong/FinalProject/assets/163672241/7edffdb9-3dd2-49d5-9142-d6e8ad3f78db">

I made sure I was in the right directory and everything. I took a look at your Makefile and it seems like it might be because you're missing a TAB in the make function - not super sure, though.

@benkeser

**Comment by ayqxiong** [comment]
issue resolved by adding tab
