### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by benkeser** [ayqxiong/FinalProject3#4]
Ok I see a few issues:

- README is out of date (as mentioned in #3)
- Your Makefile [`docker run` statement](https://github.com/ayqxiong/FinalProject/blob/45962c7962c0af7185952e74c3ab8fc81a327bbb/Makefile#L39) is not correct. please review the syntax closely
- also use `git rm` to get rid of the compiled report that is included in the repo

**Comment by ayqxiong** [comment]
updated README, added docker image reference to Makefile, fixed `docker run` syntax, removed compiled report and added .gitkeep to the directory
